name: Main Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Укажите нужную версию Go
      
      - name: Build
        run: echo "Building Go application..."
      
      - name: Test
        run: echo "Running tests..."
      
      - name: Run
        run: echo "Running application..."
